

services:
  db:
    image: postgres:16
    container_name: market-db-prod
    env_file:
      - .env.prod
    ports:
      - "5432:5432"
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    networks:
      - marketplace-net


  app:
    build: .
    container_name: marketplace-app-prod
    env_file:
      - .env.prod
    ports:
      - "8080:8080"

    networks:
      - marketplace-net

volumes:
  pgdata_prod:

networks:
  marketplace-net:
    driver: bridge
