name: Deploy Marketplace App to AWS ECS

on:
  push:
    branches:
      - main   # əgər səndə 'master'dirsə, buranı master elə

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'

      - name: Build JAR file
        run: ./gradlew clean build

      - name: Build Docker image
        run: docker build -t behruz617/marketplace-app:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push behruz617/marketplace-app:latest


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Force new ECS deployment
        uses: aws-actions/amazon-ecs-update-service@v2
        with:
          cluster: marketplace-cluster-v2
          service: marketplace-service
